project:
  type: book

book:
  title: "R-Tricks"
  author: "Nils Ratnaweera"
  chapters:
    - index.qmd
    - base-R.qmd
    - r-spatial.qmd
    - geospatial.qmd
    - ggplot.qmd
    - rstudio.qmd
    - swisstopo-api.qmd
    

execute: 
  warning: false

message: false

format:
  html:
    theme:
      - cosmo
      - brand




