project:
  type: book

book:
  title: "R-Tricks"
  author: "Norah Jones"
  date: "8/18/2025"
  chapters:
    - index.qmd
    - base-R.qmd
    - r-spatial.qmd
    - ggplot.qmd
    - rstudio.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand




